<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TempTablesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('temp_tables')->delete();
        
        \DB::table('temp_tables')->insert(array (
            0 => 
            array (
                'id' => 1,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'model_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            1 => 
            array (
                'id' => 2,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'talent_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            2 => 
            array (
                'id' => 3,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'actor_actress_type',
                'type' => 'string',
                'value' => 'movie_actor',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            3 => 
            array (
                'id' => 4,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'extra_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            4 => 
            array (
                'id' => 5,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'gender',
                'type' => 'string',
                'value' => 'female',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            5 => 
            array (
                'id' => 6,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_year',
                'type' => 'string',
                'value' => '2020',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            6 => 
            array (
                'id' => 7,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_month',
                'type' => 'string',
                'value' => '4',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            7 => 
            array (
                'id' => 8,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_day',
                'type' => 'string',
                'value' => '5',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            8 => 
            array (
                'id' => 9,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'nationality',
                'type' => 'string',
                'value' => 'Åland Islands',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:40:59',
                'updated_at' => '2023-11-25 08:40:59',
            ),
            9 => 
            array (
                'id' => 10,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'first_name',
                'type' => 'string',
                'value' => 'صابر',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            10 => 
            array (
                'id' => 11,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'first_name_furigana',
                'type' => 'string',
                'value' => '高橋',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            11 => 
            array (
                'id' => 12,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'middle_name',
                'type' => 'string',
                'value' => 'asdf',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            12 => 
            array (
                'id' => 13,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'last_name',
                'type' => 'string',
                'value' => 'طباطبایی یزدی',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            13 => 
            array (
                'id' => 14,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'last_name_furigana',
                'type' => 'string',
                'value' => '高橋',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            14 => 
            array (
                'id' => 15,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'stage_name',
                'type' => 'string',
                'value' => 'asdf',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            15 => 
            array (
                'id' => 16,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'have_other_nationality',
                'type' => 'string',
                'value' => 'no',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            16 => 
            array (
                'id' => 17,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'other_nationality',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            17 => 
            array (
                'id' => 18,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'are_you_mixed',
                'type' => 'string',
                'value' => 'no',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            18 => 
            array (
                'id' => 19,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'fathers_nationality',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            19 => 
            array (
                'id' => 20,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'mothers_nationality',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:21',
                'updated_at' => '2023-11-25 08:41:21',
            ),
            20 => 
            array (
                'id' => 21,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'eye_color',
                'type' => 'string',
                'value' => 'Brown',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 08:41:39',
            ),
            21 => 
            array (
                'id' => 22,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'current_hair_color',
                'type' => 'string',
                'value' => 'Blonde',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 08:41:39',
            ),
            22 => 
            array (
                'id' => 23,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'height',
                'type' => 'string',
                'value' => '188',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 08:41:39',
            ),
            23 => 
            array (
                'id' => 24,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'weight',
                'type' => 'string',
                'value' => '111',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 08:41:39',
            ),
            24 => 
            array (
                'id' => 25,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'bust',
                'type' => 'string',
                'value' => '111',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 08:41:39',
            ),
            25 => 
            array (
                'id' => 26,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'hips',
                'type' => 'string',
                'value' => '111',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 08:41:39',
            ),
            26 => 
            array (
                'id' => 27,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'waist',
                'type' => 'string',
                'value' => '110',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 08:41:39',
            ),
            27 => 
            array (
                'id' => 28,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'size_unit',
                'type' => 'string',
                'value' => 'uk',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 11:03:28',
            ),
            28 => 
            array (
                'id' => 29,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_jp_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 11:03:28',
            ),
            29 => 
            array (
                'id' => 30,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_uk_size',
                'type' => 'string',
                'value' => '1',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 11:04:38',
            ),
            30 => 
            array (
                'id' => 31,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_men_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 10:49:04',
            ),
            31 => 
            array (
                'id' => 32,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_women_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 10:49:04',
            ),
            32 => 
            array (
                'id' => 33,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_eu_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 10:32:27',
            ),
            33 => 
            array (
                'id' => 34,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'clothe_size',
                'type' => 'string',
                'value' => '2XL',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 08:41:39',
                'updated_at' => '2023-11-25 11:02:43',
            ),
            34 => 
            array (
                'id' => 35,
                'step_id' => 3,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'native_language',
                'type' => 'string',
                'value' => 'aa',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 11:17:14',
                'updated_at' => '2023-11-25 11:17:14',
            ),
            35 => 
            array (
                'id' => 36,
                'step_id' => 3,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'other_language',
                'type' => 'json',
                'value' => NULL,
                'text' => NULL,
                'json' => '[{"language":{"type":"select","input":"ab","text":"Abkhaz"},"level":{"type":"select","input":"Fluent","text":"Fluent"}}]',
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 11:17:14',
                'updated_at' => '2023-11-25 11:17:14',
            ),
            36 => 
            array (
                'id' => 37,
                'step_id' => 3,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'biography',
                'type' => 'text',
                'value' => NULL,
                'text' => 'Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.',
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 11:17:14',
                'updated_at' => '2023-11-25 11:17:14',
            ),
            37 => 
            array (
                'id' => 38,
                'step_id' => 3,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'skills',
                'type' => 'json',
                'value' => NULL,
                'text' => NULL,
                'json' => '[{"skills_type":{"type":"select","input":"dance_skill","text":"Dance Skill"},"other_skills":{"type":"text","input":"","text":""},"sport_skill_type":{"type":"select","input":"","text":""},"dance_skill_type":{"type":"select","input":"ballet","text":"Ballet"},"singing_skill_type":{"type":"select","input":"","text":""},"acting_skill_type":{"type":"select","input":"","text":""},"musical_instrument_skill_type":{"type":"select","input":"","text":""},"performance_skill_type":{"type":"select","input":"","text":""},"driving_skill_type":{"type":"select","input":"","text":""},"culinary_skill_type":{"type":"select","input":"","text":""},"visual_art_skill_type":{"type":"select","input":"","text":""},"sport_other_skills":{"type":"text","input":"","text":""},"dance_other_skills":{"type":"text","input":"","text":""},"singing_other_skills":{"type":"text","input":"","text":""},"acting_other_skills":{"type":"text","input":"","text":""},"musical_instrument_other_skills":{"type":"text","input":"","text":""},"performance_other_skills":{"type":"text","input":"","text":""},"driving_other_skills":{"type":"text","input":"","text":""},"culinary_other_skills":{"type":"text","input":"","text":""},"visual_art_other_skills":{"type":"text","input":"","text":""},"skills_description":{"type":"textarea","input":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n","text":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n"},"photos":{"type":"upload","input":"","text":[]},"videos":{"type":"upload","input":"","text":[]},"audios":{"type":"upload","input":"","text":[]}}]',
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 11:17:14',
                'updated_at' => '2023-11-25 11:17:14',
            ),
            38 => 
            array (
                'id' => 39,
                'step_id' => 3,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'job_experiences',
                'type' => 'json',
                'value' => NULL,
                'text' => NULL,
            'json' => '[{"type":{"type":"select","input":"film","text":"Film"},"other_type":{"type":"text","input":"","text":""},"year":{"type":"select","input":"2019","text":"2019"},"month":{"type":"select","input":"2","text":"2 (February)"},"title":{"type":"text","input":"یسبسیب","text":"یسبسیب"},"description":{"type":"textarea","input":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n","text":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n"},"photos":{"type":"upload","input":"","text":[]},"videos":{"type":"upload","input":"","text":[]},"audios":{"type":"upload","input":"","text":[]}}]',
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 11:17:14',
                'updated_at' => '2023-11-25 11:17:14',
            ),
            39 => 
            array (
                'id' => 40,
                'step_id' => 3,
                'user_id' => 3,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'job_experiences_pdf',
                'type' => 'file',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-25 11:17:14',
                'updated_at' => '2023-11-25 11:17:14',
            ),
            40 => 
            array (
                'id' => 41,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'model_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            41 => 
            array (
                'id' => 42,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'talent_type',
                'type' => 'string',
                'value' => 'talent',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            42 => 
            array (
                'id' => 43,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'actor_actress_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            43 => 
            array (
                'id' => 44,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'extra_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            44 => 
            array (
                'id' => 45,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'gender',
                'type' => 'string',
                'value' => 'female',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            45 => 
            array (
                'id' => 46,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_year',
                'type' => 'string',
                'value' => '2021',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            46 => 
            array (
                'id' => 47,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_month',
                'type' => 'string',
                'value' => '4',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            47 => 
            array (
                'id' => 48,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_day',
                'type' => 'string',
                'value' => '5',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            48 => 
            array (
                'id' => 49,
                'step_id' => 0,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'nationality',
                'type' => 'string',
                'value' => 'Åland Islands',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:06:51',
                'updated_at' => '2023-11-26 08:06:51',
            ),
            49 => 
            array (
                'id' => 50,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'first_name',
                'type' => 'string',
                'value' => 'fsdfsd',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:23',
                'updated_at' => '2023-11-26 08:07:23',
            ),
            50 => 
            array (
                'id' => 51,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'first_name_furigana',
                'type' => 'string',
                'value' => '高橋',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:23',
                'updated_at' => '2023-11-26 08:07:23',
            ),
            51 => 
            array (
                'id' => 52,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'middle_name',
                'type' => 'string',
                'value' => 'sdfg',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:23',
                'updated_at' => '2023-11-26 08:07:23',
            ),
            52 => 
            array (
                'id' => 53,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'last_name',
                'type' => 'string',
                'value' => 'طباطبایی یزدی',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:23',
                'updated_at' => '2023-11-26 08:07:23',
            ),
            53 => 
            array (
                'id' => 54,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'last_name_furigana',
                'type' => 'string',
                'value' => '高橋',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:24',
                'updated_at' => '2023-11-26 08:07:24',
            ),
            54 => 
            array (
                'id' => 55,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'stage_name',
                'type' => 'string',
                'value' => 'asdf',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:24',
                'updated_at' => '2023-11-26 08:07:24',
            ),
            55 => 
            array (
                'id' => 56,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'have_other_nationality',
                'type' => 'string',
                'value' => 'no',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:24',
                'updated_at' => '2023-11-26 08:07:24',
            ),
            56 => 
            array (
                'id' => 57,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'other_nationality',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:24',
                'updated_at' => '2023-11-26 08:07:24',
            ),
            57 => 
            array (
                'id' => 58,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'are_you_mixed',
                'type' => 'string',
                'value' => 'no',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:24',
                'updated_at' => '2023-11-26 08:07:24',
            ),
            58 => 
            array (
                'id' => 59,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'fathers_nationality',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:24',
                'updated_at' => '2023-11-26 08:07:24',
            ),
            59 => 
            array (
                'id' => 60,
                'step_id' => 1,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'mothers_nationality',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:24',
                'updated_at' => '2023-11-26 08:07:24',
            ),
            60 => 
            array (
                'id' => 61,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'eye_color',
                'type' => 'string',
                'value' => 'Blue',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            61 => 
            array (
                'id' => 62,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'current_hair_color',
                'type' => 'string',
                'value' => 'Blonde',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            62 => 
            array (
                'id' => 63,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'height',
                'type' => 'string',
                'value' => '199',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            63 => 
            array (
                'id' => 64,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'weight',
                'type' => 'string',
                'value' => '111',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            64 => 
            array (
                'id' => 65,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'bust',
                'type' => 'string',
                'value' => '109',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            65 => 
            array (
                'id' => 66,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'hips',
                'type' => 'string',
                'value' => '111',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            66 => 
            array (
                'id' => 67,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'waist',
                'type' => 'string',
                'value' => '111',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            67 => 
            array (
                'id' => 68,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'size_unit',
                'type' => 'string',
                'value' => 'eu',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            68 => 
            array (
                'id' => 69,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_jp_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            69 => 
            array (
                'id' => 70,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_uk_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            70 => 
            array (
                'id' => 71,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_men_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            71 => 
            array (
                'id' => 72,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_women_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            72 => 
            array (
                'id' => 73,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'shoe_eu_size',
                'type' => 'string',
                'value' => '16',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            73 => 
            array (
                'id' => 74,
                'step_id' => 2,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'clothe_size',
                'type' => 'string',
                'value' => '90',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:07:44',
                'updated_at' => '2023-11-26 08:07:44',
            ),
            74 => 
            array (
                'id' => 75,
                'step_id' => 3,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'native_language',
                'type' => 'string',
                'value' => 'aa',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:08:17',
                'updated_at' => '2023-11-26 08:08:17',
            ),
            75 => 
            array (
                'id' => 76,
                'step_id' => 3,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'other_language',
                'type' => 'json',
                'value' => NULL,
                'text' => NULL,
                'json' => '[{"language":{"type":"select","input":"ab","text":"Abkhaz"},"level":{"type":"select","input":"Fluent","text":"Fluent"}}]',
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:08:17',
                'updated_at' => '2023-11-26 08:08:17',
            ),
            76 => 
            array (
                'id' => 77,
                'step_id' => 3,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'biography',
                'type' => 'text',
                'value' => NULL,
                'text' => 'Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.',
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:08:17',
                'updated_at' => '2023-11-26 08:08:17',
            ),
            77 => 
            array (
                'id' => 78,
                'step_id' => 3,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'skills',
                'type' => 'json',
                'value' => NULL,
                'text' => NULL,
                'json' => '[{"skills_type":{"type":"select","input":"singing_skill","text":"Singing Skill"},"other_skills":{"type":"text","input":"","text":""},"sport_skill_type":{"type":"select","input":"","text":""},"dance_skill_type":{"type":"select","input":"","text":""},"singing_skill_type":{"type":"select","input":"techno","text":"Techno"},"acting_skill_type":{"type":"select","input":"","text":""},"musical_instrument_skill_type":{"type":"select","input":"","text":""},"performance_skill_type":{"type":"select","input":"","text":""},"driving_skill_type":{"type":"select","input":"","text":""},"culinary_skill_type":{"type":"select","input":"","text":""},"visual_art_skill_type":{"type":"select","input":"","text":""},"sport_other_skills":{"type":"text","input":"","text":""},"dance_other_skills":{"type":"text","input":"","text":""},"singing_other_skills":{"type":"text","input":"","text":""},"acting_other_skills":{"type":"text","input":"","text":""},"musical_instrument_other_skills":{"type":"text","input":"","text":""},"performance_other_skills":{"type":"text","input":"","text":""},"driving_other_skills":{"type":"text","input":"","text":""},"culinary_other_skills":{"type":"text","input":"","text":""},"visual_art_other_skills":{"type":"text","input":"","text":""},"skills_description":{"type":"textarea","input":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n","text":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n"},"photos":{"type":"upload","input":"","text":[]},"videos":{"type":"upload","input":"","text":[]},"audios":{"type":"upload","input":"","text":[]}}]',
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:08:17',
                'updated_at' => '2023-11-26 08:08:17',
            ),
            78 => 
            array (
                'id' => 79,
                'step_id' => 3,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'job_experiences',
                'type' => 'json',
                'value' => NULL,
                'text' => NULL,
            'json' => '[{"type":{"type":"select","input":"drama","text":"Drama"},"other_type":{"type":"text","input":"","text":""},"year":{"type":"select","input":"2019","text":"2019"},"month":{"type":"select","input":"3","text":"3 (March)"},"title":{"type":"text","input":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.","text":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed."},"description":{"type":"textarea","input":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n","text":"Begin with your name and current role. Detail your key skills and how they\'ve influenced your career trajectory. Summarize your professional experiences, highlighting significant achievements. Mention your educational background and any specialized training. Optionally, shed light on personal interests that offer a glimpse into your character. Wrap up with your future aspirations. Ensure your biography remains genuine, and update as needed.\\n"},"photos":{"type":"upload","input":"","text":[]},"videos":{"type":"upload","input":"","text":[]},"audios":{"type":"upload","input":"","text":[]}}]',
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:08:17',
                'updated_at' => '2023-11-26 08:08:17',
            ),
            79 => 
            array (
                'id' => 80,
                'step_id' => 3,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'job_experiences_pdf',
                'type' => 'file',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:08:17',
                'updated_at' => '2023-11-26 08:08:17',
            ),
            80 => 
            array (
                'id' => 81,
                'step_id' => 4,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'profile_image',
                'type' => 'file',
                'value' => '181189',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:09:09',
                'updated_at' => '2023-11-26 08:09:09',
            ),
            81 => 
            array (
                'id' => 82,
                'step_id' => 4,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'full_length_photo',
                'type' => 'file',
                'value' => '330812',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:09:09',
                'updated_at' => '2023-11-26 08:09:09',
            ),
            82 => 
            array (
                'id' => 83,
                'step_id' => 4,
                'user_id' => 4,
                'member_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'other_photos',
                'type' => 'file',
                'value' => '670725',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-26 08:09:09',
                'updated_at' => '2023-11-26 08:09:09',
            ),
        ));
        
        
    }
}