<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TempFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('temp_fields')->delete();

        \DB::table('temp_fields')->insert(array (
            0 =>
            array (
                'id' => 1,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'model_type',
                'request_key' => 'model_type',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'talent_type',
                'request_key' => 'talent_type',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'actor_actress_type',
                'request_key' => 'actor_actress_type',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'extra_type',
                'request_key' => 'extra_type',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'gender',
                'request_key' => 'gender',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_year',
                'request_key' => 'birhtday_year',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_month',
                'request_key' => 'birhtday_month',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_day',
                'request_key' => 'birhtday_day',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'nationality',
                'request_key' => 'nationality',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'name',
                'request_key' => 'first_name',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'first_name_furigana',
                'request_key' => 'first_name_furigana',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'middle_name',
                'request_key' => 'middle_name',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'family',
                'request_key' => 'last_name',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'last_name_furigana',
                'request_key' => 'last_name_furigana',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'stage_name',
                'request_key' => 'stage_name',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'have_other_nationality',
                'request_key' => 'have_other_nationality',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'other_nationality',
                'request_key' => 'other_nationality',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'are_you_mixed',
                'request_key' => 'are_you_mixed',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'fathers_nationality',
                'request_key' => 'fathers_nationality',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'mothers_nationality',
                'request_key' => 'mothers_nationality',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'eye_color',
                'request_key' => 'eye_color',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'current_hair_color',
                'request_key' => 'current_hair_color',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'height',
                'request_key' => 'height',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'weight',
                'request_key' => 'weight',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'bust',
                'request_key' => 'bust',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'hips',
                'request_key' => 'hips',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'waist',
                'request_key' => 'waist',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'size_unit',
                'request_key' => 'size_unit',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_jp_size',
                'request_key' => 'shoe_jp_size',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_uk_size',
                'request_key' => 'shoe_uk_size',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_men_size',
                'request_key' => 'shoe_us_men_size',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_women_size',
                'request_key' => 'shoe_us_women_size',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_eu_size',
                'request_key' => 'shoe_eu_size',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'native_language',
                'request_key' => 'native_language',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'other_language',
                'request_key' => 'other_language',
                'type' => 'json',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'biography',
                'request_key' => 'biography',
                'type' => 'text',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'skills',
                'request_key' => 'skills',
                'type' => 'json',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'job_experiences',
                'request_key' => 'job_experiences',
                'type' => 'json',
                'file_type' => NULL,
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'job_experiences_pdf',
                'request_key' => 'job_experiences_pdf',
                'type' => 'file',
                'file_type' => 'File',
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'step_id' => 4,
                'model_name' => 'Member',
                'model_field' => 'profile_image',
                'request_key' => 'profile_image',
                'type' => 'file',
                'file_type' => 'Image',
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'step_id' => 4,
                'model_name' => 'Member',
                'model_field' => 'full_length_photo',
                'request_key' => 'full_length_photo',
                'type' => 'file',
                'file_type' => 'Image',
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'step_id' => 4,
                'model_name' => 'Member',
                'model_field' => 'other_photos',
                'request_key' => 'other_photos',
                'type' => 'file',
                'file_type' => 'Image',
                'enabled_at' => '2023-11-12 13:01:08',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
                array (
                    'id' => 43,
                    'step_id' => 2,
                    'model_name' => 'Member',
                    'model_field' => 'clothe_size',
                    'request_key' => 'clothe_size',
                    'type' => 'string',
                    'file_type' => NULL,
                    'enabled_at' => '2023-11-12 13:01:08',
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
        ));


    }
}
