<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TempFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('temp_fields')->delete();
        
        \DB::table('temp_fields')->insert(array (
            0 => 
            array (
                'id' => 1,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'model_type',
                'request_key' => 'model_type',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            1 => 
            array (
                'id' => 2,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'talent_type',
                'request_key' => 'talent_type',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            2 => 
            array (
                'id' => 3,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'actor_actress_type',
                'request_key' => 'actor_actress_type',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            3 => 
            array (
                'id' => 4,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'extra_type',
                'request_key' => 'extra_type',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            4 => 
            array (
                'id' => 5,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'gender',
                'request_key' => 'gender',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            5 => 
            array (
                'id' => 6,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_year',
                'request_key' => 'birhtday_year',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            6 => 
            array (
                'id' => 7,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_month',
                'request_key' => 'birhtday_month',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            7 => 
            array (
                'id' => 8,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'birhtday_day',
                'request_key' => 'birhtday_day',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            8 => 
            array (
                'id' => 9,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'nationality',
                'request_key' => 'nationality',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            9 => 
            array (
                'id' => 10,
                'step_id' => 0,
                'model_name' => 'Member',
                'model_field' => 'name',
                'request_key' => 'first_name',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            10 => 
            array (
                'id' => 11,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'first_name_furigana',
                'request_key' => 'first_name_furigana',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            11 => 
            array (
                'id' => 12,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'middle_name',
                'request_key' => 'middle_name',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            12 => 
            array (
                'id' => 13,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'family',
                'request_key' => 'last_name',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            13 => 
            array (
                'id' => 14,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'last_name_furigana',
                'request_key' => 'last_name_furigana',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            14 => 
            array (
                'id' => 15,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'stage_name',
                'request_key' => 'stage_name',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            15 => 
            array (
                'id' => 16,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'have_other_nationality',
                'request_key' => 'have_other_nationality',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            16 => 
            array (
                'id' => 17,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'other_nationality',
                'request_key' => 'other_nationality',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            17 => 
            array (
                'id' => 18,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'are_you_mixed',
                'request_key' => 'are_you_mixed',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            18 => 
            array (
                'id' => 19,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'fathers_nationality',
                'request_key' => 'fathers_nationality',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            19 => 
            array (
                'id' => 20,
                'step_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'mothers_nationality',
                'request_key' => 'mothers_nationality',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            20 => 
            array (
                'id' => 21,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'eye_color',
                'request_key' => 'eye_color',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            21 => 
            array (
                'id' => 22,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'current_hair_color',
                'request_key' => 'current_hair_color',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            22 => 
            array (
                'id' => 23,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'height',
                'request_key' => 'height',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            23 => 
            array (
                'id' => 24,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'weight',
                'request_key' => 'weight',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            24 => 
            array (
                'id' => 25,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'bust',
                'request_key' => 'bust',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            25 => 
            array (
                'id' => 26,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'hips',
                'request_key' => 'hips',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            26 => 
            array (
                'id' => 27,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'waist',
                'request_key' => 'waist',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            27 => 
            array (
                'id' => 28,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'size_unit',
                'request_key' => 'size_unit',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            28 => 
            array (
                'id' => 29,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_jp_size',
                'request_key' => 'shoe_jp_size',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            29 => 
            array (
                'id' => 30,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_uk_size',
                'request_key' => 'shoe_uk_size',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            30 => 
            array (
                'id' => 31,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_men_size',
                'request_key' => 'shoe_us_men_size',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            31 => 
            array (
                'id' => 32,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_women_size',
                'request_key' => 'shoe_us_women_size',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            32 => 
            array (
                'id' => 33,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'shoe_eu_size',
                'request_key' => 'shoe_eu_size',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            33 => 
            array (
                'id' => 34,
                'step_id' => 2,
                'model_name' => 'Member',
                'model_field' => 'clothe_size',
                'request_key' => 'clothe_size',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            34 => 
            array (
                'id' => 35,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'native_language',
                'request_key' => 'native_language',
                'type' => 'string',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            35 => 
            array (
                'id' => 36,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'other_language',
                'request_key' => 'other_language',
                'type' => 'json',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            36 => 
            array (
                'id' => 37,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'biography',
                'request_key' => 'biography',
                'type' => 'text',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            37 => 
            array (
                'id' => 38,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'skills',
                'request_key' => 'skills',
                'type' => 'json',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            38 => 
            array (
                'id' => 39,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'job_experiences',
                'request_key' => 'job_experiences',
                'type' => 'json',
                'file_type' => '',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            39 => 
            array (
                'id' => 40,
                'step_id' => 3,
                'model_name' => 'Member',
                'model_field' => 'job_experiences_pdf',
                'request_key' => 'job_experiences_pdf',
                'type' => 'file',
                'file_type' => 'File',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            40 => 
            array (
                'id' => 41,
                'step_id' => 4,
                'model_name' => 'Member',
                'model_field' => 'profile_image',
                'request_key' => 'profile_image',
                'type' => 'file',
                'file_type' => 'Image',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            41 => 
            array (
                'id' => 42,
                'step_id' => 4,
                'model_name' => 'Member',
                'model_field' => 'full_length_photo',
                'request_key' => 'full_length_photo',
                'type' => 'file',
                'file_type' => 'Image',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            42 => 
            array (
                'id' => 43,
                'step_id' => 4,
                'model_name' => 'Member',
                'model_field' => 'other_photos',
                'request_key' => 'other_photos',
                'type' => 'file',
                'file_type' => 'Image',
                'enabled_at' => '2023-11-12 13:01:00',
                'created_at' => '2023-11-12 13:01:00',
                'updated_at' => '2023-11-12 13:01:00',
            ),
            43 => 
            array (
                'id' => 44,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'country_code',
                'request_key' => 'country_code',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'mobile_number',
                'request_key' => 'mobile_number',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'country',
                'request_key' => 'country',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'zipcode',
                'request_key' => 'zipcode',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'state',
                'request_key' => 'state',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'city',
                'request_key' => 'city',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'area',
                'request_key' => 'area',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'address',
                'request_key' => 'address',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'step_id' => 5,
                'model_name' => 'Member',
                'model_field' => 'address_2',
                'request_key' => 'address_2',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'authentication_type',
                'request_key' => 'authentication_type',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'passport_photo',
                'request_key' => 'passport_photo',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'front_photo_drive_license_card',
                'request_key' => 'front_photo_drive_license_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'back_photo_drive_license_card',
                'request_key' => 'back_photo_drive_license_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'front_photo_insurance_card',
                'request_key' => 'front_photo_insurance_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'back_photo_insurance_card',
                'request_key' => 'back_photo_insurance_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'front_photo_my_number_card',
                'request_key' => 'front_photo_my_number_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'back_photo_my_number_card',
                'request_key' => 'back_photo_my_number_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'front_photo_residence_card',
                'request_key' => 'front_photo_residence_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'step_id' => 6,
                'model_name' => 'Member',
                'model_field' => 'back_photo_residence_card',
                'request_key' => 'back_photo_residence_card',
                'type' => 'string',
                'file_type' => NULL,
                'enabled_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}