<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TempTablesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('temp_tables')->delete();
        
        \DB::table('temp_tables')->insert(array (
            0 => 
            array (
                'id' => 1,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'model_type',
                'type' => 'string',
                'value' => 'advertising_model,fitness_model',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:23:38',
            ),
            1 => 
            array (
                'id' => 2,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'talent_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:23:38',
            ),
            2 => 
            array (
                'id' => 3,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'actor_actress_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:23:38',
            ),
            3 => 
            array (
                'id' => 4,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'extra_type',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:08:30',
            ),
            4 => 
            array (
                'id' => 5,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'gender',
                'type' => 'string',
                'value' => 'male',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:23:38',
            ),
            5 => 
            array (
                'id' => 6,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'birhtday_year',
                'type' => 'string',
                'value' => '2023',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:23:38',
            ),
            6 => 
            array (
                'id' => 7,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'birhtday_month',
                'type' => 'string',
                'value' => '1',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:23:38',
            ),
            7 => 
            array (
                'id' => 8,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'birhtday_day',
                'type' => 'string',
                'value' => '1',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:23:38',
            ),
            8 => 
            array (
                'id' => 9,
                'step_id' => 0,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'nationality',
                'type' => 'string',
                'value' => 'Åland Islands',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:08:30',
                'updated_at' => '2023-11-24 09:08:30',
            ),
            9 => 
            array (
                'id' => 10,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'first_name_furigana',
                'type' => 'string',
                'value' => '高橋',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 10:20:35',
            ),
            10 => 
            array (
                'id' => 11,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'middle_name',
                'type' => 'string',
                'value' => 'tabatabaee',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 09:51:09',
            ),
            11 => 
            array (
                'id' => 12,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'last_name_furigana',
                'type' => 'string',
                'value' => '島高橋高橋高橋高橋高橋',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 09:51:09',
            ),
            12 => 
            array (
                'id' => 13,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'stage_name',
                'type' => 'string',
                'value' => 'adf',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 09:20:51',
            ),
            13 => 
            array (
                'id' => 14,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'have_other_nationality',
                'type' => 'string',
                'value' => 'yes',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 09:51:09',
            ),
            14 => 
            array (
                'id' => 15,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'other_nationality',
                'type' => 'string',
                'value' => 'Albania,Algeria,Andorra,Angola',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 10:04:21',
            ),
            15 => 
            array (
                'id' => 16,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'are_you_mixed',
                'type' => 'string',
                'value' => 'yes',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 10:16:33',
            ),
            16 => 
            array (
                'id' => 17,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'fathers_nationality',
                'type' => 'string',
                'value' => 'Afghanistan',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 10:16:33',
            ),
            17 => 
            array (
                'id' => 18,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'mothers_nationality',
                'type' => 'string',
                'value' => 'Åland Islands',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 10:16:33',
            ),
            18 => 
            array (
                'id' => 19,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'eye_color',
                'type' => 'string',
                'value' => 'Amber',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            19 => 
            array (
                'id' => 20,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'current_hair_color',
                'type' => 'string',
                'value' => 'Brown',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            20 => 
            array (
                'id' => 21,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'height',
                'type' => 'string',
                'value' => '188',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            21 => 
            array (
                'id' => 22,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'weight',
                'type' => 'string',
                'value' => '122',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            22 => 
            array (
                'id' => 23,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'bust',
                'type' => 'string',
                'value' => '122',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            23 => 
            array (
                'id' => 24,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'hips',
                'type' => 'string',
                'value' => '121',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            24 => 
            array (
                'id' => 25,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'waist',
                'type' => 'string',
                'value' => '122',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            25 => 
            array (
                'id' => 26,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'size_unit',
                'type' => 'string',
                'value' => 'us',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            26 => 
            array (
                'id' => 27,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'shoe_jp_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            27 => 
            array (
                'id' => 28,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'shoe_uk_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            28 => 
            array (
                'id' => 29,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_men_size',
                'type' => 'string',
                'value' => '1.5C',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            29 => 
            array (
                'id' => 30,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'shoe_us_women_size',
                'type' => 'string',
                'value' => '1.5C',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            30 => 
            array (
                'id' => 31,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'shoe_eu_size',
                'type' => 'string',
                'value' => NULL,
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            31 => 
            array (
                'id' => 32,
                'step_id' => 2,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'clothe_size',
                'type' => 'string',
                'value' => '90',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:25:22',
                'updated_at' => '2023-11-24 09:25:22',
            ),
            32 => 
            array (
                'id' => 33,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'first_name',
                'type' => 'string',
                'value' => 'saber',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 09:20:51',
                'updated_at' => '2023-11-24 09:20:51',
            ),
            33 => 
            array (
                'id' => 34,
                'step_id' => 1,
                'user_id' => 3,
                'member_id' => 1,
                'model_name' => 'Member',
                'model_field' => 'last_name',
                'type' => 'string',
                'value' => 'طباطبائییزدی',
                'text' => NULL,
                'json' => NULL,
                'approved_at' => NULL,
                'admin_id' => 1,
                'created_at' => '2023-11-24 10:20:35',
                'updated_at' => '2023-11-24 10:20:35',
            ),
        ));
        
        
    }
}